EC2 - CloudWatch unified agent

diff --git a/ec2/ec2-cloudwatch.yaml b/ec2/ec2-cloudwatch.yaml
--- a/ec2/ec2-cloudwatch.yaml
+++ b/ec2/ec2-cloudwatch.yaml
@@ -42,6 +42,11 @@ Parameters:
     Type: String
     Default: t2.micro
 
+  CloudWatchLogPath:
+    Description: Cloudwatch Log Path
+    Type: String
+    Default: cwlogs
+
 Resources:
 
   Ec2IAMRole:
@@ -123,16 +128,117 @@ Resources:
         - !Ref Ec2SecurityGroup
       SubnetId: !Ref VpcEc2Subnet
       UserData:
-        Fn::Base64: |
-          #!/bin/bash
-          yum update -y
-          yum install -y httpd
-          systemctl start httpd
-          systemctl enable httpd
-          echo "<h1>Hello from $(hostname -f)</h1>" > /var/www/html/index.html
+        "Fn::Base64":
+          !Sub |
+            #!/bin/bash
+            yum update -y
+            if [ ! -f /swapfile ]; then dd if=/dev/zero of=/swapfile bs=1M count=256; chmod 600 /swapfile; mkswap /swapfile; swapon /swapfile; fi
+            yum install -y httpd
+            systemctl start httpd
+            systemctl enable httpd
+            echo "<h1>Hello from $(hostname -f)</h1>" > /var/www/html/index.html
+            rpm -Uvh https://s3.amazonaws.com/amazoncloudwatch-agent/amazon_linux/amd64/latest/amazon-cloudwatch-agent.rpm
+            /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a stop
+            /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c ssm:${CloudWatchAgentParameter} -s
+            /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a start
+            #yum update -y aws-cfn-bootstrap
+            #/opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource Ec2AutoScalingGroup --region ${AWS::Region}
       Tags:
         - Key: Environment
           Value: "dev"
+
+
+
+  CloudWatchAgentParameter:
+    Type: AWS::SSM::Parameter
+    Properties:
+      Name: !Sub 'AmazonCloudWatch-agent-config'
+      Type: String
+      Value: !Sub |
+        {
+          "logs": {
+            "logs_collected": {
+              "files": {
+                "collect_list": [
+                  {
+                    "file_path": "/var/log/httpd/error_log",
+                    "log_group_name": "${LogGroupHttpdErrorLog}"
+                  },
+                  {
+                    "file_path": "/var/log/httpd/access_log",
+                    "log_group_name": "${LogGroupHttpdAccessLog}"
+                  }
+                ]
+              }
+            }
+          },
+          "metrics": {
+            "append_dimensions": {
+              "AutoScalingGroupName": "${!aws:AutoScalingGroupName}",
+              "ImageId": "${!aws:ImageId}",
+              "InstanceId": "${!aws:InstanceId}",
+              "InstanceType": "${!aws:InstanceType}"
+            },
+            "metrics_collected": {
+              "mem": {
+                "measurement": [
+                  "mem_used_percent"
+                ],
+                "metrics_collection_interval": 60
+              },
+              "cpu": {
+                "measurement": [
+                  {"name": "cpu_usage_idle", "unit": "Percent"},
+                  {"name": "cpu_usage_nice", "unit": "Percent"}
+                ],
+                "metrics_collection_interval": 60
+              },
+              "processes": {
+                "measurement": [
+                  "total"
+                ],
+                "metrics_collection_interval": 60
+              },
+              "netstat": {
+                "measurement": [
+                  "tcp_established"
+                ],
+                "metrics_collection_interval": 60
+              },
+              "disk": {
+                "measurement": [
+                  "used_percent"
+                ],
+                "resources": [
+                  "/"
+                ],
+                "ignore_file_system_types": [
+                  "xfs"
+                ],
+                "metrics_collection_interval": 300
+              },
+              "swap": {
+                "measurement": [
+                  "swap_used_percent"
+                ],
+                "metrics_collection_interval": 300
+              }
+            }
+          }
+        } 
+      Description: !Sub 'CloudWatch agent config for /${CloudWatchLogPath}'
+
+  LogGroupHttpdErrorLog:
+    Type: AWS::Logs::LogGroup
+    Properties:
+      LogGroupName: !Sub '/${CloudWatchLogPath}/cloudwatch-agent/httpd/error_log'
+      RetentionInDays: 1
+
+  LogGroupHttpdAccessLog:
+    Type: AWS::Logs::LogGroup
+    Properties:
+      LogGroupName: !Sub '/${CloudWatchLogPath}/cloudwatch-agent/httpd/access_log'
+      RetentionInDays: 1
 
 Outputs:
 
